### ISSUE TITLE
update to 8.1 ?

### ISSUE THREAD

**Issue by iddoeldor** [mzpqnxow/gdb-static-cross#2]
https://sourceware.org/gdb/wiki/BuildingCrossGDBandGDBserver

**Comment by mzpqnxow** [comment]
I’m not sure what the URL is about, but if I get a day and can find and/or rebuild my toolchains fircesch architecture, I’ll start to get some 8.1 binaries up with better documentation on the cross-compiling (start to finish- the article you listed takes for granted a configured cross compiler, the hard work for me was getting the vendor SDLs/toolchains (especially the Lexra mips chip) and for the ARM “old” ABI (gcc dropped OABI support before version 3, I think, and has no intention if supporting it again.

@iddeldorvany notable things in the 8.- changelog to suggest this worth the effort?

I really need to keep track of my toolchains better...

**Comment by ttimasdf** [comment]
For reference, use `cross_configure  CXXFLAGS="-fPIC -static -static-libstdc++ -static-libgcc"` instead of passing them in `make` command solved some weird issues when compiling, for gdb 8.1.

**Comment by mzpqnxow** [comment]
@ttimasdf thanks for that, it seems a much less hackish way of doing things. I will actually add it to the cross_configure alias

**Comment by mzpqnxow** [comment]
> [sourceware.org/gdb/wiki/BuildingCrossGDBandGDBserver](https://sourceware.org/gdb/wiki/BuildingCrossGDBandGDBserver)

This doesn't build a **statically linked** executable as far as I can tell.. the point of this is to build an executable that can with any libc, since you will encounter different libc's on different devices (i.e. dietlibc, uClibc, musl) as well as different versions- wildly different when dealing with some devices, which may have extremely old uClibc
